with source as (
      select * from "L01_Stage"."sfa"."dbo_OutletOrderH"
),
renamed as (
    select
        "Country_Code",
        "OlCard_id",
        "OrderNo",
        "OlOrderDate",
        "OrderExecutionDate",
        "PayForm_id",
        "ResponsiblePerson",
        "OLOrderAmount",
        "Discount",
        "Cust_id",
        "ConsumerUnit",
        "OrderYear",
        "OrderMonth",
        "OrderWeek",
        "OlDeliveryAddress",
        "VATCalcMode",
        "VAT_Sum",
        "ProxySeries",
        "ProxyNumber",
        "ProxyDate",
        "TransportCost",
        "Operation_id",
        "W_id",
        "Comments",
        "IsReturn",
        "TaxFactureNo",
        "IsLocalProducts",
        "HasUnboundPayments",
        "SyncWithDBF",
        "DLM",
        "PayDate",
        "IsConfirm",
        "OrderInPackages",
        "OrderingTime",
        "Signature",
        "PComp_id",
        "CustNumber",
        "PayFormType",
        "InvestmentId",
        "NextVisitDate",
        "Postpay",
        "SyncMMDate",
        "PCDistr_id",
        "DistributorEntity",
        "IsPromoActivity",
        "PromoActivities_ID",
        "AcceptStatus",
        "BaseOrderNo",
        "AgreementId",
        "Valid_From",
        "Valid_To"

    from source
)
select * from renamed